Build locally first, then push to DockerHub
Based on the comment from @ArturKlauser
(https://github.com/mvdan/sh/pull/638#discussion_r532089154), the author
of the first buildx CI workflow, here is the workflow suggested for
building and pushing docker images:
  - build against a local docker registry
  - test locally
  - push on DockerHub if tests passes
  - update the description on DockerHub

Note: previous test was using a generated sh script, as we already have
bash script in the repo (docker entry-point.sh), we decided to use it
instead (and the script has been validate with shfmt).

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,18 +37,22 @@ jobs:
       run: docker run -v="$PWD:/pwd" -w=/pwd -e=CGO_ENABLED=0 golang:1.15-alpine go test ./...
 
   docker:
-    name: Build and deploy Docker images
+    name: Build and test Docker images
     # Only deploy if previous stages pass.
     needs: [test, test-linux-alpine]
     runs-on: ubuntu-latest
-    if: >
-      github.event_name == 'push' &&
-        (github.ref == 'refs/heads/master' ||
-         startsWith(github.ref, 'refs/tags/')) &&
-      github.repository == 'mvdan/sh'
+    services:
+      registry:
+        image: registry:2
+        ports:
+          - 5000:5000
+        # this is needed because we restart the docker daemon for experimental
+        # support
+        options: "--restart always"
     env:
       # Export environment variables for all stages.
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
+      DOCKER_DEPLOY_IMAGES: false
       # Pushing READMEs to Dockerhub currently only works with username/password
       # and not with personal access tokens (Step: Update DockerHub description)
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
@@ -70,28 +74,26 @@ jobs:
       # Get "https://proxy.golang.org/...": local error: tls: unexpected message
       # Get "https://proxy.golang.org/...": x509: certificate signed by unknown authority
     steps:
-    - name: Check GitHub settings
-      run: |
-        missing=()
-        [[ -n "${{ secrets.DOCKER_USER }}" ]] || missing+=(DOCKER_USER)
-        [[ -n "${{ secrets.DOCKER_PASSWORD }}" ]] || missing+=(DOCKER_PASSWORD)
-        for i in "${missing[@]}"; do
-          echo "Missing github secret: $i"
-        done
-        (( ${#missing[@]} == 0 )) || exit 1
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0 # also fetch tags for 'git describe'
+    # Enable docker daemon experimental support (for 'pull --platform').
+    - name: Enable experimental support
+      run: |
+        config='/etc/docker/daemon.json'
+        if [[ -e "$config" ]]; then
+          sudo sed -i -e 's/{/{ "experimental": true, /' "$config"
+        else
+          echo '{ "experimental": true }' | sudo tee "$config"
+        fi
+        sudo systemctl restart docker
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
-    - name: Set up Docker Buildx
+    - name: Set up Docker Buildx (local builds)
       uses: docker/setup-buildx-action@v1
-    - name: Login to DockerHub
-      uses: docker/login-action@v1
       with:
-        username: ${{ secrets.DOCKER_USER }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+        driver-opts: network=host
     - name: Set up env vars
       run: |
         set -vx
@@ -102,58 +104,87 @@ jobs:
         elif echo "$GITHUB_REF" | grep -q '^refs/tags/'; then
           # Pushes tag - deploy tag name.
           echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
-        fi
-        echo "DOCKER_BASE=${{ secrets.DOCKER_USER }}/${{ env.DOCKER_REPO }}" >> $GITHUB_ENV
-        echo "DOCKER_BUILD_PLATFORMS=${DOCKER_PLATFORMS// /,}" >> $GITHUB_ENV
-    - name: Build and push
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./cmd/shfmt/Dockerfile
-        platforms: ${{ env.DOCKER_BUILD_PLATFORMS }}
-        push: true
-        tags: ${{ env.DOCKER_BASE }}:${{ env.TAG }}
-    - name: Build and push (alpine)
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./cmd/shfmt/Dockerfile
-        platforms: ${{ env.DOCKER_BUILD_PLATFORMS }}
-        push: true
-        tags: ${{ env.DOCKER_BASE }}:${{ env.TAG }}-alpine
-        target: alpine
-    - name: Test multi-architecture Docker images
-      run: |
-        # Enable docker daemon experimental support (for 'pull --platform').
-        config='/etc/docker/daemon.json'
-        if [[ -e "$config" ]]; then
-          sudo sed -i -e 's/{/{ "experimental": true, /' "$config"
         else
-          echo '{ "experimental": true }' | sudo tee "$config"
+          # Use commit SHA for PR
+          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
         fi
-        sudo systemctl restart docker
-        printf '%s\n' "#!/bin/sh" "echo 'hello world'" >myscript
+        echo "DOCKER_BASE=test/${{ env.DOCKER_REPO }}" >> $GITHUB_ENV
+        echo "DOCKER_BUILD_PLATFORMS=${DOCKER_PLATFORMS// /,}" >> $GITHUB_ENV
+    - name: Build and push to local registry
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./cmd/shfmt/Dockerfile
+        platforms: ${{ env.DOCKER_BUILD_PLATFORMS }}
+        push: true
+        tags: localhost:5000/${{ env.DOCKER_BASE }}:${{ env.TAG }}
+    - name: Build and push to local registry (alpine)
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./cmd/shfmt/Dockerfile
+        platforms: ${{ env.DOCKER_BUILD_PLATFORMS }}
+        push: true
+        tags: localhost:5000/${{ env.DOCKER_BASE }}:${{ env.TAG }}-alpine
+        target: alpine
+    - name: Test multi-arch Docker images locally
+      run: |
         for platform in $DOCKER_PLATFORMS; do
           for ext in '' '-alpine'; do
-            image="${DOCKER_BASE}:${TAG}${ext}"
+            image="localhost:5000/${DOCKER_BASE}:${TAG}${ext}"
             msg="Testing docker image $image on platform $platform"
             line="${msg//?/=}"
             printf "\n${line}\n${msg}\n${line}\n"
             docker pull -q --platform "$platform" "$image"
-            if [ -n "$ext" ]; then
+            if [[ -n "$ext" ]]; then
               echo -n "Image architecture: "
               docker run --rm --entrypoint /bin/sh "$image" -c 'uname -m'
             fi
             version=$(docker run --rm "$image" --version)
             echo "shfmt version: $version"
-            if [ "$TAG" != 'latest' -a "$TAG" != "$version" ]; then
+            if [[ $TAG != "latest" ]] &&
+            [[ $TAG != "$version" ]] &&
+            ! echo "$version" | grep -q "$TAG"; then
               echo "Version mismatch: shfmt $version tagged as $TAG"
               exit 1
             fi
-            docker run --rm -v "$PWD:/mnt" -w '/mnt' "$image" -d myscript
+            docker run --rm -v "$PWD:/mnt" -w '/mnt' "$image" -d cmd/shfmt/docker-entrypoint.sh
           done
         done
+    - name: Check GitHub settings
+      if: >
+        github.event_name == 'push' &&
+        (github.ref == 'refs/heads/master' ||
+        startsWith(github.ref, 'refs/tags/')) &&
+        github.repository == 'mvdan/sh'
+      run: |
+        missing=()
+        [[ -n "${{ secrets.DOCKER_USER }}" ]] || missing+=(DOCKER_USER)
+        [[ -n "${{ secrets.DOCKER_PASSWORD }}" ]] || missing+=(DOCKER_PASSWORD)
+        for i in "${missing[@]}"; do
+          echo "Missing github secret: $i"
+        done
+        (( ${#missing[@]} == 0 )) || exit 1
+        echo "DOCKER_DEPLOY_IMAGES=true" >> $GITHUB_ENV
+    - name: Login to DockerHub
+      if: ${{ env.DOCKER_DEPLOY_IMAGES == 'true' }}
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKER_USER }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Push images to DockerHub
+      if: ${{ env.DOCKER_DEPLOY_IMAGES == 'true' }}
+      run: |
+        for ext in '' '-alpine'; do
+          image_src="${DOCKER_BASE}:${TAG}${ext}"
+          image_dst="${{ secrets.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${TAG}${ext}"
+          msg="Copy multi-arch docker images to DockerHub ($image)"
+          line="${msg//?/=}"
+          printf "\n${line}\n${msg}\n${line}\n"
+          skopeo copy --all --src-tls-verify=0 docker://localhost:5000/$image_src docker://docker.io/$image_dst
+        done
     - name: Update DockerHub description
+      if: ${{ env.DOCKER_DEPLOY_IMAGES == 'true' }}
       uses: peter-evans/dockerhub-description@v2
       with:
         username: ${{ secrets.DOCKER_USER }}
